### Ping
GET http://localhost:8080/recipes/1
 
### Test POST with Form Values
POST http://localhost:8080/recipes
Content-Type: application/x-www-form-urlencoded

name=Testingsdad

### Get recipes with pagination
GET http://localhost:8080/recipes
Content-Type: application/json


### Create Meal Prep
POST http://localhost:8080/mealprep
Content-Type: application/json
{
    "user_id": 1,
    "name": "Oktober 2 - 2",
    "recipe_ids": [1, 2]
}

##Get Meal
GET http://localhost:8080/mealprep
### Add Recipe 
POST http://localhost:8080/mealprep/recipe
Content-Type: application/json

{
    "meal_prep_id": 99,
    "recipe_id": 1
}

### Get ingredients by mealprep
GET http://localhost:8080/mealprep/1
Content-Type: application/json
